package dev.ziriuz.mcp.services;

import io.modelcontextprotocol.client.McpSyncClient;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.ai.mcp.SyncMcpToolCallbackProvider;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

import java.util.List;
import java.util.Optional;

@Service
public class DatabaseChatService {

    private final ChatClient chatClient;
    private static final String UNKNOWN_RESPONSE = "I don't know";
    private static final String ASSISTANT_INSTRUCTION = """
    You are Database retrieval agent.
    Convert user query to SQL and call available tools to execute SQL and get data.
    When generating final response, just return correct response generated by tool.
    """;
    private static final String DB_DESCRIPTION = """
    Orders management database contains tables:
    ##############
    `products` table (
    - `id`: a unique identifier for each product (primary key);
    - `name`: the name of the product;
    - `price`: the price of the product;
    )
    ##############
    `customer_orders` table (
    - `order_id`: a unique identifier for each order (primary key);
    - `customer_id`: the ID of the customer who made the order;
    - `order_date`: the date the order was made;
    - `total`: the total cost of the order;
    - `status`: the status of the order (e.g. "pending", "shipped", etc.);
    )
    ##############
    `order_items` table (
    - `order_id`: the ID of the order this item belongs to (foreign key)
    - `product_id`: the ID of the product being ordered
    - `quantity`: the quantity of the product being ordered
    )
    ##############
    This suggests that each order is associated with a customer, and each order has multiple items (products) with specific quantities. The products table stores information about all available products, while the order_items table links each order to its corresponding products.
    """;


    public DatabaseChatService(
            ChatClient.Builder builder,
            ChatMemory chatMemory,
            List<McpSyncClient> mcpClients//,
            //ConversationalResponse conversationalResponse
    ) {
        chatClient = builder
                .defaultAdvisors(MessageChatMemoryAdvisor.builder(chatMemory).build())
                //.defaultTools(conversationalResponse)
                .defaultToolCallbacks(new SyncMcpToolCallbackProvider(mcpClients))
                .defaultSystem(ASSISTANT_INSTRUCTION)
                .defaultSystem("You have access to Database. Here is description of that Database: \n\n" + DB_DESCRIPTION)
                .build();
    }

    public String getResponse(String query) {
        var response = chatClient.prompt(query).call().chatResponse();
        return Optional.ofNullable(response)
                .map(r -> r.getResult().getOutput().getText())
                .orElse(UNKNOWN_RESPONSE);
    }

    public Flux<String> streamResponse(String query) {
        return chatClient.prompt(query).stream().chatResponse()
                .map(response -> response.getResult().getOutput().getText());
    }

    public Mono<String> getResponseAsMono(String query){
        return Mono.fromSupplier(() -> this.getResponse(query))
                .subscribeOn(Schedulers.boundedElastic());
    }

    @Tool(name = "crm_assistant", description = "Call this whenever you need information about: products, customers and orders")
    public String getAgentResponse(String query) {
        return this.getResponse(query);
    }
}
